package com.example.hp.materialdesign.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hp.materialdesign.domain.NewsDetail;
import com.example.hp.materialdesign.domain.User;
import com.example.hp.materialdesign.domain.ImageUrl;
import com.example.hp.materialdesign.domain.Join.UserJoinNewsBrowse;
import com.example.hp.materialdesign.domain.Join.UserJoinNewsColl;
import com.example.hp.materialdesign.domain.Join.UserJoinNewsComment;
import com.example.hp.materialdesign.domain.Channel;

import com.example.hp.materialdesign.greenDao.NewsDetailDao;
import com.example.hp.materialdesign.greenDao.UserDao;
import com.example.hp.materialdesign.greenDao.ImageUrlDao;
import com.example.hp.materialdesign.greenDao.UserJoinNewsBrowseDao;
import com.example.hp.materialdesign.greenDao.UserJoinNewsCollDao;
import com.example.hp.materialdesign.greenDao.UserJoinNewsCommentDao;
import com.example.hp.materialdesign.greenDao.ChannelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsDetailDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig imageUrlDaoConfig;
    private final DaoConfig userJoinNewsBrowseDaoConfig;
    private final DaoConfig userJoinNewsCollDaoConfig;
    private final DaoConfig userJoinNewsCommentDaoConfig;
    private final DaoConfig channelDaoConfig;

    private final NewsDetailDao newsDetailDao;
    private final UserDao userDao;
    private final ImageUrlDao imageUrlDao;
    private final UserJoinNewsBrowseDao userJoinNewsBrowseDao;
    private final UserJoinNewsCollDao userJoinNewsCollDao;
    private final UserJoinNewsCommentDao userJoinNewsCommentDao;
    private final ChannelDao channelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsDetailDaoConfig = daoConfigMap.get(NewsDetailDao.class).clone();
        newsDetailDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        imageUrlDaoConfig = daoConfigMap.get(ImageUrlDao.class).clone();
        imageUrlDaoConfig.initIdentityScope(type);

        userJoinNewsBrowseDaoConfig = daoConfigMap.get(UserJoinNewsBrowseDao.class).clone();
        userJoinNewsBrowseDaoConfig.initIdentityScope(type);

        userJoinNewsCollDaoConfig = daoConfigMap.get(UserJoinNewsCollDao.class).clone();
        userJoinNewsCollDaoConfig.initIdentityScope(type);

        userJoinNewsCommentDaoConfig = daoConfigMap.get(UserJoinNewsCommentDao.class).clone();
        userJoinNewsCommentDaoConfig.initIdentityScope(type);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        newsDetailDao = new NewsDetailDao(newsDetailDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        imageUrlDao = new ImageUrlDao(imageUrlDaoConfig, this);
        userJoinNewsBrowseDao = new UserJoinNewsBrowseDao(userJoinNewsBrowseDaoConfig, this);
        userJoinNewsCollDao = new UserJoinNewsCollDao(userJoinNewsCollDaoConfig, this);
        userJoinNewsCommentDao = new UserJoinNewsCommentDao(userJoinNewsCommentDaoConfig, this);
        channelDao = new ChannelDao(channelDaoConfig, this);

        registerDao(NewsDetail.class, newsDetailDao);
        registerDao(User.class, userDao);
        registerDao(ImageUrl.class, imageUrlDao);
        registerDao(UserJoinNewsBrowse.class, userJoinNewsBrowseDao);
        registerDao(UserJoinNewsColl.class, userJoinNewsCollDao);
        registerDao(UserJoinNewsComment.class, userJoinNewsCommentDao);
        registerDao(Channel.class, channelDao);
    }
    
    public void clear() {
        newsDetailDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        imageUrlDaoConfig.clearIdentityScope();
        userJoinNewsBrowseDaoConfig.clearIdentityScope();
        userJoinNewsCollDaoConfig.clearIdentityScope();
        userJoinNewsCommentDaoConfig.clearIdentityScope();
        channelDaoConfig.clearIdentityScope();
    }

    public NewsDetailDao getNewsDetailDao() {
        return newsDetailDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ImageUrlDao getImageUrlDao() {
        return imageUrlDao;
    }

    public UserJoinNewsBrowseDao getUserJoinNewsBrowseDao() {
        return userJoinNewsBrowseDao;
    }

    public UserJoinNewsCollDao getUserJoinNewsCollDao() {
        return userJoinNewsCollDao;
    }

    public UserJoinNewsCommentDao getUserJoinNewsCommentDao() {
        return userJoinNewsCommentDao;
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

}
