package com.example.hp.materialdesign.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.hp.materialdesign.domain.Join.UserJoinNewsBrowse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_JOIN_NEWS_BROWSE".
*/
public class UserJoinNewsBrowseDao extends AbstractDao<UserJoinNewsBrowse, Long> {

    public static final String TABLENAME = "USER_JOIN_NEWS_BROWSE";

    /**
     * Properties of entity UserJoinNewsBrowse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, Long.class, "userId", false, "USER_ID");
        public final static Property NewsId = new Property(2, Long.class, "newsId", false, "NEWS_ID");
        public final static Property BrowseDate = new Property(3, java.util.Date.class, "browseDate", false, "BROWSE_DATE");
    }


    public UserJoinNewsBrowseDao(DaoConfig config) {
        super(config);
    }
    
    public UserJoinNewsBrowseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_JOIN_NEWS_BROWSE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" INTEGER," + // 1: userId
                "\"NEWS_ID\" INTEGER," + // 2: newsId
                "\"BROWSE_DATE\" INTEGER);"); // 3: browseDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_JOIN_NEWS_BROWSE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserJoinNewsBrowse entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        Long newsId = entity.getNewsId();
        if (newsId != null) {
            stmt.bindLong(3, newsId);
        }
 
        java.util.Date browseDate = entity.getBrowseDate();
        if (browseDate != null) {
            stmt.bindLong(4, browseDate.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserJoinNewsBrowse entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        Long newsId = entity.getNewsId();
        if (newsId != null) {
            stmt.bindLong(3, newsId);
        }
 
        java.util.Date browseDate = entity.getBrowseDate();
        if (browseDate != null) {
            stmt.bindLong(4, browseDate.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserJoinNewsBrowse readEntity(Cursor cursor, int offset) {
        UserJoinNewsBrowse entity = new UserJoinNewsBrowse( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // newsId
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)) // browseDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserJoinNewsBrowse entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setNewsId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setBrowseDate(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserJoinNewsBrowse entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserJoinNewsBrowse entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserJoinNewsBrowse entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
